language: node_js
node_js:
  - "node"
  - "10"
  - "8"
install:
  - npm install -g typescript
  - npm install
after_success:
  - jest --coverage --detectOpenHandles --coverageReporters=text-lcov | coveralls